### ISSUE TITLE
PMFA_L1 warns of empty H matrix

### ISSUE THREAD

**Issue by eladnoor** [aalto-ics-kepaco/PMFA#1]
Hi,

I'm trying to run your example script `allL.m` and I get the following warning:
`Warning: Quadratic matrix (H) is empty or all zero. Your problem is linear. Consider calling LINPROG instead.` [see line 118 in PMFA_L1.m](https://github.com/aalto-ics-kepaco/PMFA/blob/master/Code/PMFA_L1.m#L118).
I tried to understand why this happens by reading the script, and there are a few unclear operations that eventually lead to the CovP matrix being zero.

In line 78, Tcov is set to be the negative of the covariance matrix, and therefore has no positive eigenvalues. CovP is supposed to be a projection on the space of positive eigenvectors, but that is, of course, empty.

**Comment by sahelybhadra** [comment]
Yes your observation is correct. This is true for first component. but
while calculating higher order components deflated currCov may not be a PSD
matrix any more. That time H part of Quadprog may not be empty.

**Comment by eladnoor** [comment]
Thank you for the quick reply.
So if I understand correctly, finding the first component in PMFA_L1 does not require `quadprog`, so I can replace it with `linprog` when `CovP` is zero?

**Comment by sahelybhadra** [comment]
Yes! Please go ahead.
Regards
Sahely Bhadra
Assistant Professor
Computer Science and Engineering
Indian Institute of Technology(IIT), Palakkad.
